model:
  type: clip
  model_name: clip-vit-large-patch14-336
  model_path: /home/bzq999/data/compmech/models/clip-vit-large-patch14-336/ 
  batch_size: 32
  device: auto
  features_dir: /home/bzq999/data/compmech/features
  extract_language: False
  tower_name: vision_model
  projection_name: visual_projection


probe:
  type: logistic
  cv_folds: 5
  n_repeats: 2
  output_dir: results/
  seed: 42
  specific_attribute: ['a_bird']

dataset:
  path: /home/bzq999/data/compmech/mcrae-x-things.hf/