model:
  type: dinov2
  model_name: dinov2-base
  model_path: /home/bzq999/data/compmech/models/dinov2-base/
  layer: -1
  batch_size: 32
  device: auto
  features_dir: /home/bzq999/data/compmech/features

dataset:
  path: /home/bzq999/data/compmech/mcrae-x-things.hf/