model:
  type: dinov2
  model_name: dinov2-base
  model_path: /leonardo_work/EUHPC_D12_071/projects/complex-clip/models/dinov2-base
  batch_size: 32
  device: auto
  features_dir: /leonardo_work/EUHPC_D27_102/compmech/features
  extract_language: False
  tower_name:
  projection:

probe:
  type: logistic
  cv_folds: 5
  n_repeats: 2
  output_dir: results/
  seed: 42
  specific_attribute: ['a_bird']


dataset:
  path: /leonardo_work/EUHPC_D27_102/compmech/whatsup_vlms_data/hf/controlled_images.hf/