# Experiment Configuration File

# Dataset Configuration
dataset:
  concept_file: "external_data/raw/mcrae-x-things.json"
  attribute_file: "external_data/raw/mcrae-x-things-taxonomy.json"
  image_dir: "external_data/raw/images"
  hf_dataset_path: "external_data/processed/hf_datasets/mcrae_x_things"

# Model Configurations
models:
  dinov2_small:
    extractor_type: "dinov2"
    model_name: "facebook/dinov2-small"
    layer: "last"
    batch_size: 64
    
  dinov2_base:
    extractor_type: "dinov2"
    model_name: "facebook/dinov2-base"
    layer: "last"
    batch_size: 32
    
  dinov2_large:
    extractor_type: "dinov2"
    model_name: "facebook/dinov2-large"
    layer: "last"
    batch_size: 16
    
  clip_base:
    extractor_type: "clip"
    model_name: "openai/clip-vit-base-patch32"
    batch_size: 32

# Probe Configurations  
probes:
  logistic:
    probe_type: "logistic"
    random_seed: 42
    
  mlp:
    probe_type: "mlp"
    random_seed: 42
    
  torch_mlp:
    type: "torch"
    hidden_dims: [512, 256]
    dropout: 0.1
    learning_rate: 0.001
    batch_size: 64
    epochs: 100

# Cross-validation Configuration
cross_validation:
  cv_folds: 5
  n_repeats: 2
  strategy: "concept_based"  # or "sample_based"
  test_size: 0.2
  random_seed: 42

# Experiment Settings
experiments:
  baseline_replication:
    model: "dinov2_base"
    probe: "logistic"
    description: "Baseline replication experiment"
    
  model_comparison:
    models: ["dinov2_small", "dinov2_base", "dinov2_large"]
    probe: "logistic"
    description: "Compare different model sizes"
    
  probe_comparison:
    model: "dinov2_base" 
    probes: ["logistic", "mlp", "torch_mlp"]
    description: "Compare different probe types"
    
  layer_analysis:
    model: "dinov2_base"
    probe: "logistic"
    layers: ["last", 6, 8, 10, 11]
    description: "Analyze different layer representations"

# Output Configuration
output:
  results_dir: "outputs/results"
  models_dir: "outputs/models"
  plots_dir: "outputs/plots"
  logs_dir: "outputs/logs"

# Caching Configuration
caching:
  cache_dir: "external_data/cached_features"
  force_recompute: false
  
# Monitoring Configuration
monitoring:
  use_wandb: false
  wandb_project: "attribute-probes"
  wandb_entity: null  # Set your username/team
  log_frequency: 100