model:
  type: paligemma2
  model_name: paligemma2-3b-ft-docci-448
  model_path: /leonardo_scratch/fast/EUHPC_D27_102/models/paligemma2-3b-ft-docci-448
  batch_size: 16
  device: auto
  features_dir: /leonardo_work/EUHPC_D27_102/compmech/features
  extract_vision: True
  extract_language: True
  tower_name:
  projection_name:


probe:
  type: logistic
  cv_folds: 5
  n_repeats: 2
  output_dir: results/
  seed: 42
  specific_attribute:

dataset:
  path: /leonardo_work/EUHPC_D27_102/compmech/whatsup_vlms_data/hf/controlled_images.hf